apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXItaG9zdDo1MDAwIjp7InVzZXJuYW1lIjoiZG9ja191c2VyIiwicGFzc3dvcmQiOiJkb2NrX3Bhc3N3b3JkIiwiZW1haWwiOiJkb2NrX3VzZXJAZG9ja2VyLWhvc3QiLCJhdXRoIjoiWkc5amExOTFjMlZ5T21SdlkydGZjR0Z6YzNkdmNtUT0ifX19
kind: Secret
metadata:
  name: private-reg-cred
type: kubernetes.io/dockerconfigjson

---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      imagePullSecrets: 
      - name: private-reg-cred
      containers:
        - name: flask-app
          image: docker-host:5000/flask-app:public
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 

---
apiVersion: v1
kind: Service 
metadata: 
  name: flask-app-svc
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
    - port: 8080 
      targetPort: 8080
